### ISSUE TITLE
Multi-Sig Wallet support.

### ISSUE THREAD

**Issue by EhtishamSabir** [camfairchild/bittensor#847] opened 2022-07-20 12:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm looking for multi-sig transactions as it comes with polkadot blockchain.
**Describe the solution you'd like**
can you guys enable multi-sig transactions & you can easily open this on https://staging.opentensor.ai/#/accounts
so I can easily test?
**Describe alternatives you've considered**
Once testing is complete then we can move multi-sig on deployment. as multi-sig is already in the explorer cloned from polkadot.
**Additional context**
![image](https://user-images.githubusercontent.com/36196667/179976827-a8b319aa-4ed2-4108-abf2-c4fa41a96310.png)

Regards
Ehti & @hueymahl

**Comment by hueymahl** [comment] 2022-07-20 15:42
As a little more context, we are developing an opens-source multi-sig wallet using the polkadot tools that can be used by the community at large.  We have a specific need for one, but want to donate our work to the cause.

Currently we have created the wallet and it is partly functional - we can send tao to it but we can't send from it.  To send from the multi-sig wallet, or stake/unstake to a hotkey, we believe we need for multi-signature calls to be enabled on bittensor.

**Comment by camfairchild** [comment] 2022-08-29 17:17
Closed as this issue is for https://github.com/opentensor/subtensor

**Closed as not planned by camfairchild** 2022-08-29 17:17 UTC
